#!/usr/bin/env python3

import os
import sys
from tempfile import TemporaryDirectory

os.environ['GIT_PAGER'] = ''
from fake_git import check_call

with TemporaryDirectory() as t:
    os.chdir(t)
    for line in sys.stdin.read().split('\n'):
        if len(line) == 0:
            continue
        print('$ ' + line)
        sys.stdout.flush()
        check_call(['sh', '-c', line])
